### ISSUE TITLE
received unexpected bytes

### ISSUE THREAD

**Issue by rsmck** [scottlamb/hikvision-tftpd#2]
On completion I get the following;

```Thu Jun  1 17:05:33 2017: 58187 / 58187 [#####################################################]
Thu Jun  1 17:05:33 2017: done!
Thu Jun  1 17:05:53 2017: received unexpected bytes '53574b4807000000000000000000000000000000' from 192.0.0.64:51019```

And the camera doesn't reboot thereafter.

Any suggestions would be greatly appreciated.

**Comment by scottlamb** [comment]
Sounds frustrating.

I have some questions that I hope will help us understand what's going on:

   * What software version were you flashing to?
   * What was the state of your camera before? i.e., was it working or bricked, and what version did it have on it?
   * Do you know if it was a Chinese region model? I gather from forums that Hikvision has some sort of region locking so they can sell the product for different prices in different regions or something.
   * What do you mean exactly by the camera doesn't reboot thereafter? it doesn't respond to pings? what IP(s) did you try? the one it was using before? 192.168.0.0.64?
   * If you power cycle it again, what happens? do you see the same "unexpected bytes" line?

There's an [official Hikvision tftp server](http://onlinetechadvice.blogspot.com/2015/12/hikvision-tftp-tool.html), although it's only for Windows. Can you run that? Personally I don't have a Windows machine, but I have used it from within a Windows virtual machine on my Mac with bridged networking. It was a pain but it worked. If the official client does something different from mine, perhaps it will unbrick your camera. If you can a packet trace of it doing so, we can make mine match its behavior.

You could also try writing on the [ipcamtalk forums](https://ipcamtalk.com/forums/hikvision.5/); someone may have an idea there.

**Comment by scottlamb** [comment]
I'm closing, as there's nothing I can do now. If you can get some/all of the information above, I'll take another look.
