### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Randomjunk999** [scottlamb/hikvision-tftpd#8]
I get:

./hikvision_ftfpd.py: 8: ./hikvision_tftpd.py: Syntax Error: newline unexpected

(Running on Ubuntu in VirtualBox with the "$ sudo ./hikvision_tftpd.py --server-ip=172.9.18.80 --filename=digicap.mav" version of the command)

**Comment by Randomjunk999** [comment]
Hi,
It's Ubuntu 18.04 with Python 3.6.5 (What are you using to run & I'll try that one.)

**Comment by scottlamb** [comment]
Ahh, I developed this with Python 2. So I think this is a dupe of #5. I'm playing around with upgrading, but the workaround is to do `sudo python2 hikvision_tftpd.py ...`
